apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nodeimageset-controller
  namespace: system
  labels:
    app.kubernetes.io/component: nodeimageset-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: nodeimageset-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/component: nodeimageset-controller
    spec:
      securityContext:
        runAsUser: 0 # Run as root to mount containerd socket
      containers:
      - args:
          - --zap-log-level=debug
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: nodeimageset-controller:dev
        imagePullPolicy: Never
        name: nodeimageset-controller
        volumeMounts:
          - name: containerd-sock
            mountPath: /run/containerd/containerd.sock
          - name: host-dir
            mountPath: /etc/containerd/certs.d
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      volumes:
        - name: containerd-sock
          hostPath:
            path: /run/containerd/containerd.sock
        - name: host-dir
          hostPath:
            path: /etc/containerd/certs.d
      serviceAccountName: imageprefetch-controller
      terminationGracePeriodSeconds: 10
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
