---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ofen-cybozu-io-v1-imageprefetch
  failurePolicy: Fail
  name: mimageprefetch.kb.io
  rules:
  - apiGroups:
    - ofen.cybozu.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - imageprefetches
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ofen-cybozu-io-v1-imageprefetch
  failurePolicy: Fail
  name: vimageprefetch.kb.io
  rules:
  - apiGroups:
    - ofen.cybozu.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - imageprefetches
  sideEffects: None
