# permissions for end users to edit nodeimagesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ofen
    app.kubernetes.io/managed-by: kustomize
  name: nodeimageset-editor-role
rules:
- apiGroups:
  - ofen.cybozu.io
  resources:
  - nodeimagesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ofen.cybozu.io
  resources:
  - nodeimagesets/status
  verbs:
  - get
