---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imageprefetch-controller-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ofen.cybozu.io
  resources:
  - imageprefetches
  - nodeimagesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ofen.cybozu.io
  resources:
  - imageprefetches/finalizers
  - nodeimagesets/finalizers
  verbs:
  - update
- apiGroups:
  - ofen.cybozu.io
  resources:
  - imageprefetches/status
  - nodeimagesets/status
  verbs:
  - get
  - patch
  - update
