---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ofen.cybozu.io
  resources:
  - imageprefetches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ofen.cybozu.io
  resources:
  - imageprefetches/finalizers
  - nodeimagesets/finalizers
  verbs:
  - update
- apiGroups:
  - ofen.cybozu.io
  resources:
  - imageprefetches/status
  - nodeimagesets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ofen.cybozu.io
  resources:
  - nodeimagesets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
