// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/cybozu-go/ofen/api/v1"
	internal "github.com/cybozu-go/ofen/internal/applyconfigurations/internal"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ImagePrefetchApplyConfiguration represents a declarative configuration of the ImagePrefetch type for use
// with apply.
//
// ImagePrefetch is the Schema for the imageprefetches API
type ImagePrefetchApplyConfiguration struct {
	metav1.TypeMetaApplyConfiguration    `json:",inline"`
	*metav1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                                 *ImagePrefetchSpecApplyConfiguration   `json:"spec,omitempty"`
	Status                               *ImagePrefetchStatusApplyConfiguration `json:"status,omitempty"`
}

// ImagePrefetch constructs a declarative configuration of the ImagePrefetch type for use with
// apply.
func ImagePrefetch(name, namespace string) *ImagePrefetchApplyConfiguration {
	b := &ImagePrefetchApplyConfiguration{}
	b.WithName(name)
	b.WithNamespace(namespace)
	b.WithKind("ImagePrefetch")
	b.WithAPIVersion("ofen.cybozu.io/v1")
	return b
}

// ExtractImagePrefetchFrom extracts the applied configuration owned by fieldManager from
// imagePrefetch for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// imagePrefetch must be a unmodified ImagePrefetch API object that was retrieved from the Kubernetes API.
// ExtractImagePrefetchFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractImagePrefetchFrom(imagePrefetch *apiv1.ImagePrefetch, fieldManager string, subresource string) (*ImagePrefetchApplyConfiguration, error) {
	b := &ImagePrefetchApplyConfiguration{}
	err := managedfields.ExtractInto(imagePrefetch, internal.Parser().Type("com.github.cybozu-go.ofen.api.v1.ImagePrefetch"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(imagePrefetch.Name)
	b.WithNamespace(imagePrefetch.Namespace)

	b.WithKind("ImagePrefetch")
	b.WithAPIVersion("ofen.cybozu.io/v1")
	return b, nil
}

// ExtractImagePrefetch extracts the applied configuration owned by fieldManager from
// imagePrefetch. If no managedFields are found in imagePrefetch for fieldManager, a
// ImagePrefetchApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// imagePrefetch must be a unmodified ImagePrefetch API object that was retrieved from the Kubernetes API.
// ExtractImagePrefetch provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractImagePrefetch(imagePrefetch *apiv1.ImagePrefetch, fieldManager string) (*ImagePrefetchApplyConfiguration, error) {
	return ExtractImagePrefetchFrom(imagePrefetch, fieldManager, "")
}

// ExtractImagePrefetchStatus extracts the applied configuration owned by fieldManager from
// imagePrefetch for the status subresource.
func ExtractImagePrefetchStatus(imagePrefetch *apiv1.ImagePrefetch, fieldManager string) (*ImagePrefetchApplyConfiguration, error) {
	return ExtractImagePrefetchFrom(imagePrefetch, fieldManager, "status")
}

func (b ImagePrefetchApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ImagePrefetchApplyConfiguration) WithKind(value string) *ImagePrefetchApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *ImagePrefetchApplyConfiguration) WithAPIVersion(value string) *ImagePrefetchApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ImagePrefetchApplyConfiguration) WithName(value string) *ImagePrefetchApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *ImagePrefetchApplyConfiguration) WithGenerateName(value string) *ImagePrefetchApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ImagePrefetchApplyConfiguration) WithNamespace(value string) *ImagePrefetchApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *ImagePrefetchApplyConfiguration) WithUID(value types.UID) *ImagePrefetchApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *ImagePrefetchApplyConfiguration) WithResourceVersion(value string) *ImagePrefetchApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *ImagePrefetchApplyConfiguration) WithGeneration(value int64) *ImagePrefetchApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *ImagePrefetchApplyConfiguration) WithCreationTimestamp(value apismetav1.Time) *ImagePrefetchApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *ImagePrefetchApplyConfiguration) WithDeletionTimestamp(value apismetav1.Time) *ImagePrefetchApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *ImagePrefetchApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *ImagePrefetchApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *ImagePrefetchApplyConfiguration) WithLabels(entries map[string]string) *ImagePrefetchApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *ImagePrefetchApplyConfiguration) WithAnnotations(entries map[string]string) *ImagePrefetchApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *ImagePrefetchApplyConfiguration) WithOwnerReferences(values ...*metav1.OwnerReferenceApplyConfiguration) *ImagePrefetchApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *ImagePrefetchApplyConfiguration) WithFinalizers(values ...string) *ImagePrefetchApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *ImagePrefetchApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &metav1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *ImagePrefetchApplyConfiguration) WithSpec(value *ImagePrefetchSpecApplyConfiguration) *ImagePrefetchApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *ImagePrefetchApplyConfiguration) WithStatus(value *ImagePrefetchStatusApplyConfiguration) *ImagePrefetchApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *ImagePrefetchApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *ImagePrefetchApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *ImagePrefetchApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *ImagePrefetchApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
