apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ include "ofen.name" . }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "ofen.chart" . }}'
  name: '{{ template "ofen.fullname" . }}-registry-allowlist'
  namespace: '{{ .Release.Namespace }}'
data:
  {{- with .Values.allowRegistries }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
