apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ofen.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ofen.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: {{ include "ofen.name" . }}
