apiVersion: ofen.cybozu.io/v1
kind: ImagePrefetch
metadata:
  name: valid-replicas-imageprefetch
spec:
  images:
    - ghcr.io/cybozu/ubuntu:24.04
    - ghcr.io/cybozu/ubuntu-debug:24.04
  replicas: 2
  nodeSelector:
    valid-key: valid-value
  imagePullSecrets:
    - name: pull-secret1
---
apiVersion: ofen.cybozu.io/v1
kind: ImagePrefetch
metadata:
  name: invalid-images-imageprefetch
spec:
  images: []
  replicas: 2
---
apiVersion: ofen.cybozu.io/v1
kind: ImagePrefetch
metadata:
  name: invalid-node-selector-imageprefetch
spec:
  images:
    - ghcr.io/cybozu/ubuntu:24.04
  replicas: 2
  nodeSelector:
    valid-key: valid-value
  allNodes: true
---
apiVersion: ofen.cybozu.io/v1
kind: ImagePrefetch
metadata:
  name: invalid-replicas-imageprefetch
spec:
  images:
    - ghcr.io/cybozu/ubuntu:24.04
  replicas: 0
---
apiVersion: ofen.cybozu.io/v1
kind: ImagePrefetch
metadata:
  name: empty-imagepullsecrets-imageprefetch
spec:
  images:
    - ghcr.io/cybozu/ubuntu:24.04
  replicas: 2
  imagePullSecrets:
    - name: ""
---
apiVersion: ofen.cybozu.io/v1
kind: ImagePrefetch
metadata:
  name: not-permitted-registry-imageprefetch
spec:
  images:
    - registry.invalid/not-permitted-image:latest
  replicas: 2
---
apiVersion: ofen.cybozu.io/v1
kind: ImagePrefetch
metadata:
  name: invalid-nodeselector-imageprefetch
spec:
  images:
    - ghcr.io/cybozu/ubuntu:24.04
  replicas: 2
  nodeSelector:
    invalid-value: ""
---
apiVersion: ofen.cybozu.io/v1
kind: ImagePrefetch
metadata:
  name: valid-allnodes-imageprefetch
spec:
  images:
    - ghcr.io/cybozu/ubuntu:24.04
  allNodes: true
---
apiVersion: ofen.cybozu.io/v1
kind: ImagePrefetch
metadata:
  name: negative-replicas-imageprefetch
spec:
  images:
    - ghcr.io/cybozu/ubuntu:24.04
  replicas: -1
